app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
 */

Route::get('/', ['uses' => 'HomeController@index', 'as' => 'index']);

Route::get('contact', ['uses' => 'HomeController@contact', 'as' => 'contact']);

Route::post('contact', ['uses' => 'HomeController@contactrequest', 'as' => 'contactrequest']);

Route::get('preview/{id}', ['uses' => 'HomeController@preview', 'as' => 'preview']);

Route::get('cart/add/{id}', ['uses' => 'CartController@cartadd', 'as' => 'cartadd']);

Route::get('cart/remove/{id}', ['uses' => 'CartController@cartremove', 'as' => 'cartremove']);

Route::get('cart/coupon/add/{coupon?}', ['uses' => 'CartController@cartcouponadd', 'as' => 'cartcouponadd']);

Route::get('cart/coupon/remove/{coupon?}', ['uses' => 'CartController@cartcouponremove', 'as' => 'cartcouponremove']);

Route::get('cart/update/{id}/{qty}', ['uses' => 'CartController@cartupdate', 'as' => 'cartupdate']);

Route::get('cart/checkout', ['uses' => 'CartController@cartcheckout', 'as' => 'cartcheckout']);

Route::get('cart/register', ['uses' => 'CartController@cartregister', 'as' => 'cartregister']);

Route::post('cart/signup', ['uses' => 'UserController@signup', 'as' => 'signup']);

Route::group(['before' => 'auth'], function () {
    Route::get('cart/shippingaddress', ['uses' => 'UserController@shippingaddress', 'as' => 'shippingaddress']);

    Route::post('cart/shippingaddress', ['uses' => 'UserController@postshippingaddress', 'as' => 'postshippingaddress']);

    Route::post('cart/billingaddress', ['uses' => 'UserController@postbillingaddress', 'as' => 'postbillingaddress']);

    Route::get('orders', ['uses' => 'UserController@orders', 'as' => 'myorders']);

    Route::get('profile', ['uses' => 'UserController@profile', 'as' => 'profile']);

    Route::post('profile', ['uses' => 'UserController@postprofile', 'as' => 'postprofile']);

    Route::get('placeorder', ['uses' => 'UserController@placeorder', 'as' => 'placeorder']);

    Route::post('placeorder', ['uses' => 'UserController@postplaceorder', 'as' => 'postplaceorder']);
});

Route::get('forbidden', array('uses' => 'UserController@forbidden', 'as' => 'forbidden'));

Route::get('login', ['uses' => 'AuthController@getLogin', 'as' => 'login']);

Route::post('login', ['uses' => 'AuthController@postLogin', 'as' => 'authenticate']);

Route::get('logout', ['uses' => 'AuthController@getLogout', 'as' => 'logout']);

Route::get('forbidden', ['uses' => 'AuthController@forbidden', 'as' => 'forbidden']);

Route::group(['before' => 'auth|manageparameters'], function () {
    Route::resource('user', 'UserController');

    Route::resource('category', 'CategoryController');

    Route::resource('brand', 'BrandController');

    Route::resource('coupon', 'CouponController');

    Route::resource('loginparam', 'LoginController');
});

Route::group(['before' => 'auth|managecontent'], function () {
    Route::resource('product', 'ProductController');
});

Route::group(array('before' => 'auth|usertypeadminstrict'), function () {
    Route::get('adminuserlist', ['uses' => 'UserController@adminuserlist', 'as' => 'adminuserlist']);

    // caution! this is a very dangerous route. it is used to enable admin user to login as a different user.
    Route::get('loginusingid/{id}', array('as' => 'loginusingid', 'uses' => 'UserController@loginusingid'))->where('id', '[0-9]+');
});

app/views/partials/deletebutton.blade.php
{{ Form::open(array('method'=>'DELETE', 'route' => array($destroyRoute, $destroyId))) }}
{{ Form::submit('Delete Record', ['class' => 'btn btn-danger btn-xs tooltips',  'data-placement' => 'right', 'data-original-title' => 'Record will be deleted immediately!', 'id' => 'btn-delete_' . $destroyId, 'disabled']) }}
{{ Form::checkbox('delete', 0, false, ['onclick' => 'if ($(this).is(\':checked\')) { $(\'#btn-delete_' . $destroyId . '\').removeAttr(\'disabled\'); } else { $(\'#btn-delete_' . $destroyId . '\').attr(\'disabled\', \'disabled\'); } ']) }}
{{ Form::close() }}

app/views/partials/errors.blade.php
@if (Session::has('message'))
	<div class="row">
		<div class="col-md-12">
			<div class="alert alert-info">
				<a class="close" data-dismiss="alert" href="#"></a>
				<ul>
					<li>{{ Session::get('message') }}</li>
				</ul>
			</div>
		</div>
	</div>
@endif

@if ($errors->any())
	<div class="row">
		<div class="col-md-12">
			<div class="alert alert-danger">
				<a class="close" data-dismiss="alert" href="#"></a>
				<ul>
					{{ implode('', $errors->all('<li>:message</li>')) }}
				</ul>
			</div>
		</div>
	</div>
@endif

app/views/partials/navbar.blade.php
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ URL::to('/') }}">SHOPIE</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{{URL::route('contact')}}">Contact</a></li>
        <li><a href="{{URL::route('cartcheckout')}}">My Cart ({{Cart::count();}})</a></li>
        @if (Auth::check() and in_array(Auth::user()->usertype_id, [10,20,30]))
          <li><a href="{{ URL::route('myorders') }}">My Orders ({{Auth::user()->orders->count();}})</a></li>
          @if (Auth::check() and in_array(Auth::user()->usertype_id, [10,20]))
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Setup <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li class="dropdown-header"><h4>Inventory</h4></li>
              <li><a href="{{ URL::route('product.index') }}">Products</a></li>
              <li class="divider"></li>
              <li class="dropdown-header"><h4>Parameters</h4></li>
              <li><a href="{{URL::route('category.index')}}">Categories</a></li>
              <li><a href="{{URL::route('brand.index')}}">Brands</a></li>
              <li><a href="{{ URL::route('coupon.index') }}">Coupons</a></li>
              @if (Auth::user()->usertype_id === 10)
              <li class="divider"></li>
              <li class="dropdown-header"><h4>Security</h4></li>
              <li><a href="{{URL::route('adminuserlist')}}">Users</a></li>
              @endif
              <li class="divider"></li>
              <li class="dropdown-header"><h4>Statistics</h4></li>
              <li><a href="{{URL::route('loginparam.index')}}">Logins</a></li>
            </ul>
          </li>
          @endif
        @endif
      </ul>
      <ul class="nav navbar-nav navbar-right" id="navbar-login">
        @if (Auth::check())
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ Auth::user()->username }} <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            @if (Auth::check() and in_array(Auth::user()->usertype_id, [10,20,30]))
              <li><a href="{{URL::route('profile')}}">Profile</a></li>
            @endif
            <li><a href="{{URL::route('logout')}}">Sign Out</a></li>
          </ul>
        </li>
        @else
        <li>
          <a href="{{ URL::route('login') }}">Sign In</a>
        </li>
        @endif
      </ul>

      @if (Route::is('index'))
      {{ Form::open( ['route' => ['index'], 'method' => 'GET', 'files' => false, 'class' => 'navbar-form navbar-right', 'role' => 'search'] ) }}
      <div class="input-group" id="navbar-search">
        {{ Form::text('fts', Input::get('fts', null), ['class' => 'form-control', 'placeholder' => 'Search']) }}
        <div class="input-group-btn">
          <button class="btn btn-success" type="submit"><i class="glyphicon glyphicon-search"></i></button>
        </div>
      </div>
      {{ Form::close() }}
      @endif

    </div><!--/.nav-collapse -->
  </div>
</div>